#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(00)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(0##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(10)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(1##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(20)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(2##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(30)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(3##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(40)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(4##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(50)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(5##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(60)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(6##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(70)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(7##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(80)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(8##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(90)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(9##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(a0)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(a##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(b0)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(b##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(c0)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(c##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(d0)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(d##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(e0)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(e##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX256(f0)
#define AUTO_GEN_ARRAY_INDEX16(x) AUTO_GEN_ARRAY_INDEX256(f##x)
#include "auto_gen_array16.h"
#undef AUTO_GEN_ARRAY_INDEX16
#endif
