#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(0)
X(AUTO_GEN_ARRAY_INDEX16(0))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(1)
X(AUTO_GEN_ARRAY_INDEX16(1))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(2)
X(AUTO_GEN_ARRAY_INDEX16(2))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(3)
X(AUTO_GEN_ARRAY_INDEX16(3))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(4)
X(AUTO_GEN_ARRAY_INDEX16(4))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(5)
X(AUTO_GEN_ARRAY_INDEX16(5))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(6)
X(AUTO_GEN_ARRAY_INDEX16(6))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(7)
X(AUTO_GEN_ARRAY_INDEX16(7))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(8)
X(AUTO_GEN_ARRAY_INDEX16(8))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(9)
X(AUTO_GEN_ARRAY_INDEX16(9))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(a)
X(AUTO_GEN_ARRAY_INDEX16(a))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(b)
X(AUTO_GEN_ARRAY_INDEX16(b))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(c)
X(AUTO_GEN_ARRAY_INDEX16(c))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(d)
X(AUTO_GEN_ARRAY_INDEX16(d))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(e)
X(AUTO_GEN_ARRAY_INDEX16(e))
#endif
#if AUTO_GEN_ARRAY_SIZE > AUTO_GEN_ARRAY_INDEX16(f)
X(AUTO_GEN_ARRAY_INDEX16(f))
#endif
